webAPP/PaymentApp/urls.py
from django.urls import path
from . import views

app_name="PaymentApp"

urlpatterns = [
    path('checkout/', views.CheckOut, name='checkout'),
    # path('payment-success/', views.PaymentSuccessful, name='payment-success'),
    # path('payment-failed/', views.PaymentSuccessful, name='payment-failed'), 
    ]

webAPP/cart/urls.py
from django.urls import path, include
from . import views

app_name="cart"

urlpatterns = [
    path("", views.cart_summary, name="cart_summary"), #main url pattern for the cart
    path('add/', views.cart_add, name="cart_add"), #url pointing to add page
    path('delete/', views.cart_delete, name="cart_delete"), #url pointing to delete page
    path('update/', views.cart_update, name="cart_update"), #url pointing to update page
]
  

webAPP/webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace="cart")),  #reference to created url file for cart
    path("",include("core.urlss", namespace='core')),
    path('PaymentApp/', include('PaymentApp.urls', namespace="PaymentApp")),
    path('paypal/', include('paypal.standard.ipn.urls'), name="paypal"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webAPP/PaymentApp/models.py
from django.db import models
from product.models import Product
from django.contrib.auth.models import User

#create order model
class Order(models.Model):
    #foreign key
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    full_name = models.CharField(max_length=250)
    email = models.EmailField(max_length=250)
    shipping_address = models.TextField(max_length=15000)
    amount_paid = models.DecimalField(max_digits=9, decimal_places=2)
    date_ordered = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'Order - {str(self.id)}'

# Create order items model
class OrderItem(models.Model):
    #foreign keys
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    
    quantity = models.PositiveBigIntegerField(default=1)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    
    def __str__(self):
        return f'Order Item - {str(self.id)}'

webAPP/cart/models.py
from django.db import models

# Create your models here.

webAPP/userprofile/models.py
from typing import Any
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Userprofile(models.Model):
    user= models.OneToOneField(User, related_name='userprofile', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

webAPP/product/forms.py
from django import forms

from .models import Product
#from .models import ProductReview

class ProductForm(forms.ModelForm):
    class Meta:
        model=Product
        fields = {'category','title', 'description','image','price',}

webAPP/PaymentApp/views.py
from django.shortcuts import render
from product.models import Product
from paypal.standard.forms import PayPalPaymentsForm
from django.conf import settings
import uuid
from django.urls import reverse
from cart.cart import Cart
from product.models import Product

def CheckOut(request):#, product_id):
    product=Product(request)
#product = Product.objects.get(id = product_id)
#Get the cart
    cart = Cart(request)
    cart_products = cart.get_products
    quantities = cart.get_quantities
    totals = cart.cart_total()
    
    host = request.get_host()
    
    paypal_checkout = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': product.price,
        'item_name': product.title,
        'invoice': uuid.uuid4(),
        'currency_code': 'UGX',
        'notify_url': f"https://{host}{reverse('paypal-ipn')}",
        #'return_url' : f "http://{host}{reverse('PaymentApp:payment-success')}", #, kwargs = {'product_id' : product.id }) } ",
        #'cancel_url' : f "http://{host}{reverse('PaymentApp:payment-failed')}", #, kwargs = {'product_id' : product.id }) } ",                        
    }
    
    paypal_payment = PayPalPaymentsForm(initial=paypal_checkout)
    
    #context ={
        #'product' : product,
        #'paypal': paypal_payment
    #}
    return render(request, 'core/checkout.html', {"cart_products":cart_products, "quantities":quantities, "totals":totals, 'paypal':paypal_payment})
#return render(request, 'core/checkout.html', context)

def PaymentSuccessful(request, cart_products, quantities, totals):#, product_id):
    #product = Product.objects.get(id=product_id)
    return render(request, 'core/payment-success.html', {"cart_products":cart_products, "quantities":quantities, "totals":totals})

def paymentFailed(request, cart_products, quantities, totals):#, product_id):
    #product = Product.objects.get(id=product_id)
    return render(request, 'core/payment-failed.html', {"cart_products":cart_products, "quantities":quantities, "totals":totals})

webAPP/cart/views.py
from django.shortcuts import render, get_object_or_404
from .cart import Cart
from product.models import Product
from django.http import JsonResponse
from django.contrib import messages


def cart_summary(request):
    #Get the cart
    cart = Cart(request)
    cart_products = cart.get_products
    quantities = cart.get_quantities
    totals = cart.cart_total()
    return render(request, 'core/cart_summary.html', {"cart_products":cart_products, "quantities":quantities, "totals":totals}) #returns the cart_summary.html template
    #return render(request, 'core/cart_summary.html', {})


def cart_add(request):
    #Get the cart
    cart = Cart(request)
    #test for post
    if request.POST.get('action') == 'post':
        #Get stuff
        product_id = int(request.POST.get('product_id'))
        product_qty = str(request.POST.get('product_qty'))
        #lookup product in the database
        product = get_object_or_404(Product, id=product_id)
        
        #save to session
        cart.add(product=product, quantity=product_qty)
        
        #Get cart quantity
        cart_quantity = cart.__len__()
        
        #return response
        #response=JsonResponse({'Product title: ': product.title})
        response=JsonResponse({'qty: ': cart_quantity})
        messages.success(request,("Product added to Cart..."))
        return response


def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        #Get stuff
        product_id = int(request.POST.get('product_id'))
        # Call the delete function in Cart
        cart.delete(product=product_id)
        
        response = JsonResponse({'product': product_id})
        #return redirect('cart_summary')
        messages.success(request,("Product deleted from Cart..."))
        return response

def cart_update(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        #Get stuff
        product_id = str(request.POST.get('product_id'))
        product_qty = str(request.POST.get('product_qty'))
        
        cart.update(product=product_id, quantity=product_qty)
        
        response = JsonResponse({'qty': product_qty})
        #return redirect('cart_summary')
        messages.success(request,("Cart updated..."))
        return response

webAPP/core/views.py
import logging
from django.shortcuts import render, redirect
from product.models import Product, Category
from django.http import HttpResponse
from userprofile.models import Userprofile
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django import forms
from .forms import SignUpForm, SignUpForm2, UpdateUserForm, ChangePasswordForm
from django.db.models import Q
from product.forms import ProductForm
from django.utils.text import slugify


def index(request):
    products= Product.objects.all()
    categories=Category.objects.all()
    return render(request, 'core/index.html',{'products':products, 'categories':categories})

def update_password(request):
    if request.user.is_authenticated:
        current_user = request.user
        #did user fill in the form
        if request.method == 'POST':
            form = ChangePasswordForm(current_user, request.POST)
            #is form valid
            if form.is_valid():
                form.save()
                messages.success(request, "Password has been updated...")
                login(request, current_user)
                return redirect('core:update_password')
            
            else:
                for error in list(form.errors.values()):
                    messages.error(request, error)
                    return redirect('core:update_password')
                
        else:
            form = ChangePasswordForm(current_user)
            return render(request, 'core/update_password.html', {'form':form})

    else:
       messages.success(request, "Login required to Update Password...")
       return redirect('core:index')  
       

def update_user(request):
    if request.user.is_authenticated:
        current_user = User.objects.get(id=request.user.id)
        user_form = UpdateUserForm(request.POST or None, instance=current_user)
        
        if user_form.is_valid():
            user_form.save()
            
            login(request, current_user)
            messages.success(request, "User has been Updated...")
            return redirect('core:index')
        return  render(request,'core/update_user.html',{'user_form':user_form})
    else:
        messages.success(request, "Login required to Update Profile...")
        return redirect('core:index')   

def category_summary(request):
    categories=Category.objects.all()
    return render(request,'core/category_summary.html',{'categories':categories})

def allproduct(request):
    products= Product.objects.all()
    return render(request, 'core/allproduct.html',{'products':products})

 
def about(request):
    return render(request, 'core/about.html', {})

def addproduct(request):
    return render(request, 'core/addproduct.html', {})



def myproduct(request):
    buss_id=request.user.id
    user = User.objects.get(pk=buss_id)
    return render(request, 'core/myproduct.html', {'user':user})
  

def product(request,pk):
    product= Product.objects.get(id=pk)
    return render(request, 'core/product.html',{'product':product})
# view for the homepage

def vendor_detail(request, pk):
    user = User.objects.get(pk=pk)
    return render(request, 'core/vendor_detail.html', {'user':user})


def product_detail(request, slug):
    product = Product.objects.get(slug=slug)
    return render(request, 'core/product_details.html',{'product':product})
# view for the product detail page


def base(request):
    return render(request, 'core/base.html') 

@login_required
def mystore(request):
    return render(request, 'core/mystore.html') 


def editproduct(request,pk):
    # Getting the product 
    product = Product.objects.get(id=pk)
    
    if request.method == 'POST':
        form = ProductForm(request.POST,request.FILES, instance=product)
        product.delete()
        if form.is_valid():
            product= form.save(commit=False)
            product.save()
            messages.success(request, "Product added successfully!")
            return redirect('core:myproduct')
    else:
        # If the request is GET, render the form pre-filled with product details
        form = ProductForm(instance=product)
    categories = Category.objects.all() 
    # Render the template with the form
    return render(request, 'core/editproduct.html', {'form': form, 'product': product, 'categories': categories})

def deleteProduct(request,pk):
    product = Product.objects.get(id=pk)
    product.delete()
    return render(request,'core/myproduct.html')

def addproduct(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.save()
            messages.success(request, "Product added successfully!")
            return redirect('core:myproduct')
        else:
            messages.error(request, "Form validation failed. Please correct the errors.")
    else:
        form = ProductForm() 
    categories = Category.objects.all()  
    return render(request, 'core/addproduct.html', {'form': form, 'categories': categories})


@login_required
#def myaccount(request):
    #return render(request, 'core/myaccount.html')

def search(request):
    query = request.GET.get('query','')
    products= Product.objects.filter(title__icontains=query)
    return render(request,'core/search.html',{'query':query,'product':products})

def register_user(request):
    form = SignUpForm()
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()  # Save the form data to create a new user object
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, "You have been registered!")
            return redirect('core:index')
        else:
            messages.error(request, "There was an error! Please try again.")
    return render(request, 'core/register.html', {'form': form})

def business_register(request):
    form=SignUpForm2()
    if request.method== "POST":
        form=SignUpForm2(request.POST)
        #if form has been filled
        if form.is_valid():
            user = form.save()  # Save the form data to create a new user object
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, "You have been registered!")
            return redirect('core:index')
        else:
            messages.error(request, "There was an error! Please try again.")
    return render(request, 'core/business_register.html',{'form':form}) 

#view for login_user
def login_user(request):
    if request.method=="POST":
        # filing the form is "post", so if form is filled
        username=request.POST['username']
        password=request.POST['password']
        user    =authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request,("You have been logged in!"))
            return redirect('core:index')
        else:
            messages.success(request,("There was an error!"))
        return render(request, 'core/login.html',{}) 
    else:
        return render(request, 'core/login.html',{}) 


def logout_user(request):
    logout(request)
    messages.success(request,("You have been logged out!"))
    return redirect('core:index') 
    

def category(request, foo):
    #replace hyphens
    foo= foo.replace('-', ' ')
    #grab category from url
    try:
        #look up category
        category = Category.objects.get(name=foo) 
        products = Product.objects.filter(category=category)  
        return render(request, 'core/category.html',{'products':products, 'category':category})
    except:
      messages.success(request,("That category doesn't exist...."))
      return redirect('core:index') 
      

webAPP/product/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Product, Review
from .forms import ReviewForm

# Create your views here.
def product_details(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    reviews = Review.objects.filter(product=product)
    form = ReviewForm()
    
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.product = product
            review.save()
            return HttpResponseRedirect(request.path)

    return render(request, 'product_details.html', {'product': product, 'reviews': reviews, 'form': form})
# Create your views here.

webAPP/userprofile/views.py
from django.shortcuts import render

# Create your views here.

webAPP/templates/core/base.html
{%load bootstrap5%}
{%load static%}

       
{%include 'core/navbar.html'%}
      
         {%if messages%}
            {%for message in messages%}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {%endfor%}
        {%endif%}
        {% block content %}
        {% endblock %}<br/>
        <!-- Footer-->
       


         <footer style="background-color: #75b1da; color: #051c3a;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4"> 
                    <ul>
                        <li class="topper">ABOUT US</li>
                        <li><a class="dropdown-item" href="{%url 'core:index'%}">Home</a></li>
                        <li><a class="dropdown-item" href="{%url 'core:about'%}">About</a></li>
                    </ul>   
                </div>
                <div class="col-lg-4">
                    <ul>
                        <li class="topper">Support</li>
                        <li>Safety tips</li>
                        <li>support@gula.ug</li>
                        <li>FAQ</li>
                    </ul>
                </div>
                <div class="col-lg-4">
                    <ul>
                        <li class="topper">Contact us</li>
                        <li>+256 787541120</li>
                        <li>+256 700345628</li>
                        <li>gulaadmin@gmail.com</li>
                    </ul>
                </div>
                
            </div>
        </div>
    </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static "js/scripts.js" %}"></script>
    </body>
</html>

webAPP/templates/core/business_register.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>GULAA! </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static "assets/favicon.png" %}" />
        <!-- Bootstrap icons-->
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
        <link href="{% static "css/reg.css" %}" rel="stylesheet" />
        <style>
            body {
                background-image: url('{% static "assets/bluer.jpg" %}');
                background-size: cover;
                background-position: center;
            }
        </style>
    </head>
    <div class="wrapper1">
        {%if messages%}
            {%for message in messages%}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>{{ message }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {%endfor%}
        {%endif%}
        <form class="form" method ="POST" action="">
            {%csrf_token%}
            <p>Already have an account?<a href="{%url 'core:login' %}"> Log In</a></p>
            <br></br>
            <div class= 'logo' >
                <a href ="{%url 'core:index'%}">
                    <img src="{% static "assets/bluesquare.png" %}">
                </a>
            </div>
            
            <div class="input-box {% if form.username.errors %}error{% endif %}">
                <input type="text" id="username" name="username" placeholder="Enter username" required>
                <i class='bx bxs-user'></i>
                {% if form.username.errors %}
                    <span class="error-message">{{ form.username.errors }}</span>
                {% endif %}
            </div>


            <div class="input-box {% if form.first_name.errors %}error{% endif %}">
                <input type="text" id="first_name" name="first_name" placeholder="Enter Business Name" required>
                <i class='bx bx-align-left'></i>
                {% if form.first_name.errors %}
                    <span class="error-message">{{ form.first_name.errors }}</span>
                {% endif %}
            </div>

            <div class="input-box {% if form.email.errors %}error{% endif %}">
                <input type="email" id="email" name="email" placeholder="Enter email" required>
                <i class='bx bx-align-left'></i>
                {% if form.email.errors %}
                    <span class="error-message">{{ form.email.errors }}</span>
                {% endif %}
            </div>

            <div class="input-box {% if form.password1.errors %}error{% endif %}">
                <input type="password" id="password1" name="password1" placeholder="Enter Password" required>
                <i class='bx bxs-lock-alt'></i>
                {% if form.password1.errors %}
                    <span class="error-message">{{ form.password1.errors }}</span>
                {% endif %}
            </div>

            <div class="input-box {% if form.password2.errors %}error{% endif %}">
                <input type="password" id="password2" name="password2" placeholder="Confirm Password" required>
                <i class='bx bxs-lock-alt'></i>
                {% if form.password2.errors %}
                    <span class="error-message">{{ form.password2.errors }}</span>
                {% endif %}
            </div>
            {{form.is_staff}}
            <button type="submit" class="btn">
                Register
            </button>
        </form>
    </div>
    <br></br>   

</html>

webAPP/templates/core/cart_summary.html
{%load bootstrap5%}
{%load static%}
<!DOCTYPE html>
<html lang= "en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>GULAA! </title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static "assets/favicon.png" %}" />
    <link href="{% static "css/cartview.css" %}" rel="stylesheet" />
    <!--stylesheets for editing html doc-->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link href = "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel= "stylesheet" />
    <link href = "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" rel= "stylesheet" />
    <src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <link href = "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel= "stylesheet" />
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
  </head>
    <body>
        <div class="header__bar">Bringing The Best Customers And Best Sellers Together</div>
        
        <nav class="navbar navbar-expand-lg ">
        <div class="container px-2 px-lg-3">
            <a href="{%url 'core:index'%}"><img src="{% static "assets/bluesquare.png" %}" /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{%url 'core:index'%}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{%url 'core:about'%}">About</a></li>
                {%if user.is_authenticated%}
                <li class="nav-item"><a class="nav-link" href="{%url 'core:logout'%}">Logout</a></li>
                {% if user.is_staff %}
                <li class="nav-item"><a class="nav-link" href="{%url 'core:mystore'%}">My Store</a></li>
                {% endif %}
                {%else%}
                <li class="nav-item"><a class="nav-link" href="{%url 'core:login'%}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{%url 'core:register'%}">Register </a></li>
                {% endif %}               
                </ul>
                <div class="search">
                    <form method="get" action="/search/">
                    <input type="search" name ="query" placeholder="Search">
                    </form>
                </div>
                <form class="d-flex">
                    <a href="{%url 'cart:cart_summary'%}" class="btn btn-outline-dark">  <i class="bi-cart-fill me-1"></i>Cart<span class="badge bg-dark text-white ms-1 rounded-pill" id="cart_quantity">{{ cart|length }}</span></a>
                </form>
            </div>
            </button>
        </div>
        </nav>

        <div class='topper'>
            <h2 class='shoo'>Shopping Cart</h2>
        </div>
        <div class='container3'>
            <div class='box'>
                {% if cart_products %}
                    {% for product in cart_products  %}
                        <div class='rows'>
                            <img src="{{ product.image.url }}" class="cartpic">
                            <div class= 'info'>
                                <p class='cat'>{{product.category}}</p>
                                <p class='tit'>{{product.title}}</p>
                                <button type="button" value="{{product.id}}" class="btn btn-danger delete-product" id="delete">Remove</button>
                            </div>
                            <div class='quan'>
                                <p class='cat'>Quantity</p>
                                <div class="row">
                                    <div class="col-md-12">
                                        <select class="form-select form-select-md" id="select{{product.id}}">
                                            {%for key, value in quantities.items%}
                                                {%if key == product.id|slugify %}
                                                        <option selected>{{ value }}</option>
                                                {%endif%}
                                            {%endfor%}
                                    
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>
                                            <option value="4">4</option>
                                            <option value="5">5</option>
                                        </select>
                                    </div>
                                </div>
                                <button type="button" value="{{product.id}}" class="btn btn-success update-cart" id="update">Update</button>
                            </div>
                            <div class='pricey'>
                                <p class='cat'>Price</p>
                                <h4>UGX {{ product.price }}</h4>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="rows">
                    <div class='shoper'>
                        <a href="{%url 'core:index'%}" class="btn btn-secondary">Back to shop</a>
                    </div>
                    <div class="right">
                        <h3> Total: Shs.{{totals}}</h3>
                        <a href="{%url 'PaymentApp:checkout' %}" class="btn btn-secondary">Checkout</a>
                    </div>
                </div>
            </div>
        </div>

        <script>
        //update cart
        $(document).on('click', '#update', function (e) {
            e.preventDefault();
            var id = this.value
            console.log($(`#select${id} option:selected`).text());
            $.ajax({
                type: 'POST',
                url: "{%url 'cart:cart_update'%}",
                data: {
                    product_id: id,
                    product_qty: $(`#select${id} option:selected`).text(),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post'
                },
        
                success: function (json) {
                    //console.log(json)
                    document.getElementById("cart_quantity").textContent = json.qty
                    location.reload()
                },
                error: function (xhr, errmsg, err) {
        
                }
        
        
            });
        
        
        
        })
               
                //delete product from cart
               $(document).on('click', '#delete', function(e){
               e.preventDefault();
               //grab product id
               var productid=this.value
               console.log("deleted")
               $.ajax({
                   type: 'POST',
                   url: "{% url 'cart:cart_delete' %}",
                   data: {
                       product_id: productid,
                       //product_quantity: $('#select' + productid+ 'option:selected').text(),
                       csrfmiddlewaretoken: '{{ csrf_token }}',
                       action: 'post'
                   },
                   
                   success: function(json){
                       //console.log(json)
                      // document.getElementById("cart_quantity").textContent = json.qty
                      location.reload();
                   },
                   error: function(xhr, errmsg, err){
                   
                   }
                   
               
               });
               
               
               })
               
        
        </script>
    </body>